import json
from pathlib import Path

# Explicit translations for dynamic goal/card data. These are intentionally data-only:
# no render logic, pricing or calculation logic is changed.
GOAL = {
  "NL": {
    "baseline_missing": {"title":"We hebben geen betrouwbare performance-baseline","pain":"We kennen omzet of transacties, maar weten niet hoeveel mensen werkelijk zijn binnengekomen. Daardoor is winkelperformance lastig te beoordelen.","outcome":"Creëer een betrouwbare basis voor footfall, conversie en winkelpotentieel over alle locaties.","insightFit":"Betrouwbare footfall- en conversiebaseline","questions":["Weet je hoeveel bezoekers je nodig hebt om de omzet van vandaag te realiseren?","Is de data betrouwbaar genoeg om winkels te vergelijken?","Zien winkelteams dezelfde waarheid als het hoofdkantoor?"]},
    "visitors_not_buying": {"title":"We hebben bezoekers, maar niet genoeg kopers","pain":"Traffic is zichtbaar, maar het moment, de winkel of de reden van conversielekkage is nog onduidelijk.","outcome":"Identificeer welke winkels, dagen en uren genoeg bezoekers hebben maar omzetpotentieel missen.","insightFit":"Conversielek-intelligence","questions":["Welke winkels hebben goede traffic maar zwakke sales?","Wanneer daalt conversie?","Zien teams wat ze volgende week kunnen verbeteren?"]},
    "street_vs_store": {"title":"We weten niet of het probleem op straat of in de winkel zit","pain":"Als bezoek daalt, is onduidelijk of de straat rustiger is of dat de winkel aantrekkingskracht verliest.","outcome":"Scheid daling in externe traffic van winkel­aantrekkingskracht en bereken capture rate per dag, week en campagne.","insightFit":"Capture Rate & Street Potential Intelligence","questions":["Komen er minder mensen binnen omdat de straat rustiger is?","Trekt de etalage of gevel genoeg mensen naar binnen?","Kan marketing aantonen dat het winkelbezoek heeft verhoogd?"]},
    "groups_distort_conversion": {"title":"Families en groepen laten conversie slechter lijken","pain":"Een winkel kan zwak lijken wanneer veel bezoekers als familie of groep binnenkomen en slechts één persoon waarschijnlijk koopt.","outcome":"Voeg buying-unit context toe zodat conversiegesprekken eerlijker en bruikbaarder worden.","insightFit":"Buying Unit Conversion Context","questions":["Straffen weekendcijfers winkels met veel familietraffic?","Meet je personen of echte koopkansen?","Kunnen winkelmanagers conversie met context verklaren?"]},
    "visitor_profile_unknown": {"title":"We weten niet wie onze winkels binnenkomt","pain":"Footfall toont hoeveel mensen binnenkomen, maar niet of de bezoekersmix verandert naar gender, volwassenen, kinderen, families, groepen of toekomstige leeftijdscategorieën.","outcome":"Activeer bezoekersprofiel-datasets zodat teams begrijpen wie bezoekt, wanneer de mix verandert en welke winkels de juiste doelgroep aantrekken.","insightFit":"Visitor Profile & Demographic Intelligence","questions":["Weet je of de juiste doelgroep binnenkomt?","Verschilt de bezoekersmix per winkel, dag of campagne?","Veranderen families en groepen de echte koopkans?"]},
    "stores_hard_to_compare": {"title":"Winkels worden oneerlijk vergeleken","pain":"Stadswinkels, destination stores, retail parks, toeristische locaties en flagships worden vaak vergeleken alsof ze onder dezelfde omstandigheden werken.","outcome":"Maak eerlijke peergroepen en toon echte underperformance, verborgen potentieel en benchmark gaps.","insightFit":"Portfolio Benchmark Intelligence","questions":["Vergelijk je winkels op type, grootte en context?","Welke locaties verdienen als eerste aandacht?","Kunnen regiomanagers performanceverschillen verklaren?"]},
    "staffing_feels_reactive": {"title":"Personeelsplanning en servicemomenten zijn te veel op gevoel gebaseerd","pain":"Drukke momenten zijn achteraf zichtbaar, maar servicecapaciteit moet gepland worden vóórdat commerciële kansen worden gemist.","outcome":"Stem staffing, servicefocus en winkelroutines af op echte bezoekersvraag, pieken, stille uren en conversiegaps.","insightFit":"Store Operations & Service Intelligence","questions":["Welke uren zijn druk maar commercieel zwak?","Zijn roosters gebaseerd op echte vraag?","Waar kan service verbeteren zonder te gokken?"]},
    "entrance_bounce": {"title":"Mensen stappen binnen, twijfelen en vertrekken weer","pain":"Sommige bezoekers stappen over de drempel, bekijken de entreezone, ervaren frictie zoals trappen of layout en vertrekken voordat ze een echte verkoopkans worden.","outcome":"Meet engagement en bounce bij de entree zodat teams weten of de eerste meters potentieel creëren of verliezen.","insightFit":"Entrance Engagement & Bounce Intelligence","questions":["Converteren of verliezen de eerste meters bezoekers?","Waar ontstaat frictie bij binnenkomst?","Helpt de layout om verder te winkelen?"]},
    "instore_unknown": {"title":"We weten niet wat er gebeurt nadat mensen binnenkomen","pain":"De winkel kan druk zijn, maar teams zien niet waar mensen heen gaan, wat ze overslaan, waar ze blijven hangen of welke categorie aandacht verliest.","outcome":"Gebruik zone-, journey-, heatmap- en dwell-inzichten om layout, categorie-exposure en flagship learnings te verbeteren.","insightFit":"In-store Journey & Category Intelligence","questions":["Welke zones trekken traffic maar converteren niet?","Verklaart layout of categorie de performance?","Welke flagship learnings moeten toekomstige winkels sturen?"]},
    "expansion_gut_feel": {"title":"Expansiebeslissingen leunen nog te veel op gevoel","pain":"Retailteams kiezen vaak steden of straten omdat ze goed voelen, zonder te weten of doelgroep, traffic en locatiepotentieel kloppen.","outcome":"Onderbouw opening, relocatie en formatbeslissingen met traffic, catchment en performance-logica.","insightFit":"Location Potential & Expansion Intelligence","questions":["Past deze straat bij je klantprofiel?","Ken je de verwachte traffic vóórdat je tekent?","Waar zit het grootste locatiepotentieel?"]},
    "data_not_activated": {"title":"De data bestaat, maar teams handelen er onvoldoende naar","pain":"Dashboards zijn beschikbaar, maar winkelteams hebben duidelijke prioriteiten, aanbevelingen en opvolgritme nodig.","outcome":"Zet data om in wekelijkse focus, acties per winkel, regionale prioriteiten en managementgesprekken.","insightFit":"Performance Activation & Weekly Action Intelligence","questions":["Weten teams wat ze volgende week moeten doen?","Worden inzichten opgevolgd in store meetings?","Kan management acties prioriteren?"]},
    "centre_baseline": {"title":"We kunnen niet aantonen hoe het centrum over tijd presteert","pain":"Bezoekcijfers bestaan mogelijk, maar zijn niet altijd betrouwbaar, compleet of vergelijkbaar genoeg om asset performance te sturen.","outcome":"Bouw een betrouwbare baseline voor totale bezoekers, entrees, trends en asset performance.","insightFit":"Centre Performance Baseline","questions":["Weten we of het centrum echt groeit of daalt?","Zijn alle entrees betrouwbaar gemeten?","Kunnen we periodes en jaren eerlijk vergelijken?"],"modules":["3D Entrance Counting","Centre Dashboard"]},
    "entrance_value": {"title":"We weten niet welke entrees werkelijk waarde creëren","pain":"Centra hebben meerdere entrees, maar niet elke entree draagt evenveel bij aan bezoek, tenant exposure of campagne-impact.","outcome":"Laat per entree zien waar verkeer binnenkomt, verschuift en waarde creëert voor routing, huurders en marketing.","insightFit":"Entrance Performance Intelligence","questions":["Welke entrees brengen de meeste waarde?","Verandert traffic per campagne of seizoen?","Welke entree verdient extra activatie?"],"modules":["Entrance-level Reporting","Benchmark / Index Layer"]},
    "zone_flow": {"title":"Bezoekers komen binnen, maar we weten niet waar ze heen gaan","pain":"Gangpaden, zones, verdiepingen, toiletten, F&B en anchor zones hebben allemaal een rol, maar de flow ertussen is vaak onduidelijk.","outcome":"Meet zone- en corridorflow om drukte, spreiding, faciliteitengebruik en routing te begrijpen.","insightFit":"Zone Flow Intelligence","questions":["Welke zones worden over- of onderbenut?","Waar ontstaan bottlenecks of stille zones?","Hoe gebruiken bezoekers faciliteiten en F&B?"],"modules":["3D Zone Sensors","Zone Dashboard Layer"]},
    "tenant_capture": {"title":"We kunnen tenantwaarde of tenant capture niet aantonen","pain":"Footfall in het centrum laat nog niet zien welke huurders traffic aantrekken, profiteren of kansen missen.","outcome":"Verbind mall traffic met tenant entrances om capture rate, tenant exposure en leasinggesprekken te onderbouwen.","insightFit":"Tenant Capture Intelligence","questions":["Welke huurders trekken bezoekers echt naar binnen?","Welke huurders missen traffic voor hun deur?","Kunnen we tenantgesprekken met data onderbouwen?"],"modules":["Tenant Counting","Mall-to-Tenant Analytics"]},
    "leasing_evidence": {"title":"Leasinggesprekken zijn nog te veel op mening gebaseerd","pain":"Leegstand, unitwaarde en tenantmix worden besproken met ervaring, maar missen soms harde data over traffic, catchment en categoriepotentieel.","outcome":"Maak leasing battlecards, unit heatmaps en categorie-opportunity analyses voor onderbouwde verhuurgesprekken.","insightFit":"Leasing Evidence & Unit Value Intelligence","questions":["Welke units hebben verborgen potentieel?","Welke categorie mist in het centrum?","Welke data helpt leasinggesprekken?"],"modules":["Leasing Battlecard","Unit Heatmap Layer"]},
    "catchment_geo": {"title":"We weten niet waar bezoekers vandaan komen of hoe ons verzorgingsgebied verandert","pain":"Het centrum ziet bezoekers, maar niet altijd uit welke gebieden ze komen, hoe vaak ze terugkeren of welke concurrerende locaties ze ook bezoeken.","outcome":"Gebruik geo app-data voor catchment, herkomst, bezoekfrequentie, concurrentie-overlap en marktgebiedontwikkeling.","insightFit":"Catchment & Geo App Intelligence","questions":["Welke gebieden leveren de meeste bezoekers?","Verandert het verzorgingsgebied?","Welke concurrenten delen hetzelfde publiek?"],"modules":["Geo App Data","Catchment Dashboard"]},
    "brand_affinity": {"title":"We weten niet welke merken onze bezoekers al waarderen","pain":"Voor leasing en tenantmix is het waardevol om te weten welke merken, categorieën en doelgroepen passen bij het echte bezoekersprofiel.","outcome":"Gebruik brand affinity, category gap en tenant mix analyses om betere leasingdoelen en merkproposities te maken.","insightFit":"Brand Affinity & Tenant Mix Intelligence","questions":["Welke merken passen bij onze bezoekers?","Welke categorieën missen we?","Welke tenants moeten we targeten?"],"modules":["Brand Affinity Dataset","Tenant Mix Report"]},
    "parking_mobility": {"title":"We kunnen parkeerdruk en mobiliteitspatronen niet verklaren","pain":"Retail parks en car-led centra weten vaak hoeveel auto's komen, maar minder goed wanneer parkeerdruk ontstaat of hoe lang voertuigen blijven.","outcome":"Meet auto-in/uit, bezetting en verblijftijd om parking, operations en asset performance beter te sturen.","insightFit":"Parking & Mobility Intelligence","questions":["Wanneer ontstaat parkeerdruk?","Hoe lang blijven auto's gemiddeld?","Welke ingangen of uitgangen veroorzaken frictie?"],"modules":["ANPR / Car Counting","Parking Occupancy"]},
    "anpr_origin": {"title":"We weten te weinig over internationale bezoekers en autoherkomst","pain":"Cross-border assets moeten begrijpen waar auto's vandaan komen en hoe bezoekersherkomst verandert per periode of campagne.","outcome":"Toon voertuigland/regio, internationaal aandeel en verblijftijd per bezoekersgroep waar wettelijk mogelijk.","insightFit":"ANPR Origin Intelligence","questions":["Welk aandeel auto's komt uit andere landen?","Welke regio's zijn het belangrijkst?","Verandert internationaal verkeer over tijd?"],"modules":["ANPR Origin Analytics","Cross-border Reporting"]},
    "dwell_cross_shopping": {"title":"We kunnen dwell time en cross-shopping niet goed meten","pain":"Het centrum wil begrijpen of bezoekers langer blijven, meerdere tenants bezoeken, alleen passeren of later terugkomen.","outcome":"Schat dwell time, shops per visit, cross-shopping en bezoekfrequentie met de juiste mix van sensoren, smart data en feasibility review.","insightFit":"Dwell Time & Cross-Shopping Intelligence","questions":["Blijven bezoekers lang genoeg?","Bezoeken ze meerdere tenants?","Is Re-ID haalbaar en privacy-safe voor dit asset?"],"modules":["Re-ID Feasibility","Dwell Analytics","Cross-Shopping Analysis"]},
    "visitor_profile": {"title":"We begrijpen bezoekersdemografie nog onvoldoende","pain":"Bezoekcijfers zijn zichtbaar, maar de mix van volwassenen, kinderen, families en genderpatronen maakt nog geen onderdeel uit van het assetverhaal.","outcome":"Activeer visitor profile datasets op geschikte 3D-sensoren om adult/child split, gender en later leeftijdscategorieën te begrijpen.","insightFit":"Visitor Profile Intelligence","questions":["Trekt het centrum families aan?","Verschilt het bezoekersprofiel per entree of event?","Welke demografie reageert op campagnes?"],"modules":["3D Demographics Add-on","Visitor Profile Dashboard"]},
    "event_marketing": {"title":"We kunnen events, marketing en offline bezoeken niet verbinden","pain":"Events en campagnes kosten geld, maar offline impact is vaak lastig aan te tonen in bezoek en catchment response.","outcome":"Meet event uplift, campagnerespons, social/online signalen en offline bezoeken in één overzicht.","insightFit":"Event & Marketing Impact Intelligence","questions":["Heeft het event bezoek verhoogd?","Welke gebieden reageerden op marketing?","Kunnen we offline impact aantonen?"],"modules":["Event Monitor","Marketing Impact","Geo Campaign Analysis"]},
    "asset_health": {"title":"Portfolio- en assetteams kunnen centra niet eerlijk vergelijken","pain":"Meerdere centra en retail parks hebben één vergelijkbaar beeld nodig van asset health, trend, forecast en performance drivers.","outcome":"Creëer een asset health score of Location Vitality Index om centra over tijd te vergelijken en drivers te identificeren.","insightFit":"Location Vitality Index / Asset Health Intelligence","questions":["Welke centra verbeteren of dalen?","Welke driver verklaart de score?","Kunnen assetteams appels met appels vergelijken?"],"modules":["LVI / Asset Health Index","Portfolio Dashboard","Forecasting"]}
  },
  "DE": {},
  "FR": {}
}

# Concise, professional German/French translations. Package/goal keys mirror existing English object ids.
GOAL["DE"] = {
    k: v for k, v in {
    "baseline_missing": {"title":"Wir haben keine verlässliche Performance-Basis","pain":"Wir kennen Umsätze oder Transaktionen, wissen aber nicht, wie viele Menschen tatsächlich eingetreten sind. Dadurch ist Store Performance schwer zu beurteilen.","outcome":"Eine verlässliche Basis für Footfall, Conversion und Store-Potenzial über alle Standorte schaffen.","insightFit":"Verlässliche Footfall- und Conversion-Basis","questions":["Wissen Sie, wie viele Besucher für den heutigen Umsatz nötig sind?","Ist die Datenbasis zuverlässig genug, um Stores zu vergleichen?","Sehen Store-Teams dieselbe Wahrheit wie die Zentrale?"]},
    "visitors_not_buying": {"title":"Wir haben Besucher, aber nicht genug Käufer","pain":"Traffic ist sichtbar, aber Zeitpunkt, Store oder Ursache der Conversion-Leakage sind noch unklar.","outcome":"Erkennen, welche Stores, Tage und Stunden genügend Besucher haben, aber Umsatzpotenzial verlieren.","insightFit":"Conversion-Leak-Intelligence","questions":["Welche Stores haben guten Traffic, aber schwache Sales?","Wann sinkt die Conversion?","Sehen Teams, was sie nächste Woche verbessern können?"]},
    "street_vs_store": {"title":"Wir wissen nicht, ob das Problem auf der Straße oder im Store liegt","pain":"Wenn Besuche sinken, ist unklar, ob die Straße ruhiger ist oder der Store an Anziehungskraft verliert.","outcome":"Externen Traffic-Rückgang von Store-Attraktivität trennen und Capture Rate nach Tag, Woche und Kampagne berechnen.","insightFit":"Capture Rate & Street Potential Intelligence","questions":["Kommen weniger Menschen hinein, weil die Straße ruhiger ist?","Ziehen Schaufenster oder Fassade genug Menschen an?","Kann Marketing nachweisen, dass es Store-Besuche erhöht hat?"]},
    "groups_distort_conversion": {"title":"Familien und Gruppen lassen Conversion schlechter aussehen","pain":"Ein Store kann schwach wirken, wenn viele Besucher als Familie oder Gruppe kommen und nur eine Person wahrscheinlich kauft.","outcome":"Buying-Unit-Kontext hinzufügen, damit Conversion-Diskussionen fairer und nützlicher werden.","insightFit":"Buying Unit Conversion Context","questions":["Benachteiligt Familien-Traffic die Wochenend-Conversion?","Messen Sie Personen oder echte Kaufchancen?","Können Store Manager Conversion mit Kontext erklären?"]},
    "visitor_profile_unknown": {"title":"Wir wissen nicht, wer unsere Stores betritt","pain":"Footfall zeigt, wie viele Menschen eintreten, aber nicht, ob sich der Besuchermix nach Geschlecht, Erwachsenen, Kindern, Familien, Gruppen oder späteren Alterskategorien verändert.","outcome":"Visitor-Profile-Datasets aktivieren, damit Teams verstehen, wer kommt, wann sich der Mix verändert und welche Stores die richtige Zielgruppe anziehen.","insightFit":"Visitor Profile & Demographic Intelligence","questions":["Wissen Sie, ob die richtige Zielgruppe eintritt?","Unterscheidet sich der Besuchermix nach Store, Tag oder Kampagne?","Verändern Familien und Gruppen die reale Kaufchance?"]},
    "stores_hard_to_compare": {"title":"Stores werden unfair verglichen","pain":"City Stores, Destination Stores, Retail Parks, touristische Standorte und Flagships werden oft verglichen, als hätten sie dieselben Bedingungen.","outcome":"Faire Peer Groups erstellen und echte Underperformance, verborgenes Potenzial und Benchmark Gaps sichtbar machen.","insightFit":"Portfolio Benchmark Intelligence","questions":["Vergleichen Sie Stores nach Typ, Größe und Kontext?","Welche Standorte verdienen zuerst Aufmerksamkeit?","Können Regional Manager Performance-Unterschiede erklären?"]},
    "staffing_feels_reactive": {"title":"Personalplanung und Service-Momente basieren zu stark auf Gefühl","pain":"Starke Besuchsmomente sind im Nachhinein sichtbar, aber Servicekapazität muss geplant werden, bevor Chancen verloren gehen.","outcome":"Staffing, Servicefokus und Store-Routinen an echte Besuchernachfrage, Peaks, Dead Hours und Conversion Gaps anpassen.","insightFit":"Store Operations & Service Intelligence","questions":["Welche Stunden sind stark frequentiert, aber kommerziell schwach?","Basieren Dienstpläne auf echter Nachfrage?","Wo kann Service ohne Raten verbessert werden?"]},
    "entrance_bounce": {"title":"Menschen treten ein, zögern und gehen wieder","pain":"Einige Besucher überschreiten die Schwelle, sehen Reibung wie Treppen oder Layout und verlassen den Store, bevor sie eine echte Verkaufschance werden.","outcome":"Entrance Engagement und Bounce messen, damit Teams wissen, ob die ersten Meter Potenzial schaffen oder verlieren.","insightFit":"Entrance Engagement & Bounce Intelligence","questions":["Konvertieren die ersten Meter oder verlieren sie Besucher?","Wo entsteht Reibung beim Eintritt?","Hilft das Layout beim Weiterlaufen?"]},
    "instore_unknown": {"title":"Wir wissen nicht, was nach dem Eintritt passiert","pain":"Der Store kann voll sein, aber Teams sehen nicht, wohin Menschen gehen, was sie überspringen, wo sie verweilen oder welche Kategorie Aufmerksamkeit verliert.","outcome":"Zone-, Journey-, Heatmap- und Dwell-Insights nutzen, um Layout, Kategorie-Exposure und Flagship Learnings zu verbessern.","insightFit":"In-store Journey & Category Intelligence","questions":["Welche Bereiche ziehen Traffic an, konvertieren aber nicht?","Erklären Layout oder Kategorie die Performance?","Welche Flagship Learnings sollten zukünftige Stores prägen?"]},
    "expansion_gut_feel": {"title":"Expansionsentscheidungen basieren noch zu stark auf Bauchgefühl","pain":"Retail-Teams wählen Städte oder Straßen oft nach Gefühl, ohne zu wissen, ob Zielgruppe, Traffic und Standortpotenzial stimmen.","outcome":"Eröffnungen, Relocations und Formatentscheidungen mit Traffic-, Catchment- und Performance-Logik stützen.","insightFit":"Location Potential & Expansion Intelligence","questions":["Passt diese Straße zum Kundenprofil?","Kennen Sie den erwarteten Traffic vor der Unterschrift?","Wo liegt das größte Standortpotenzial?"]},
    "data_not_activated": {"title":"Die Daten sind da, aber Teams handeln zu wenig danach","pain":"Dashboards sind verfügbar, aber Store-Teams benötigen klare Prioritäten, Empfehlungen und einen Follow-up-Rhythmus.","outcome":"Daten in wöchentlichen Fokus, Store-Aktionen, regionale Prioritäten und Managementgespräche übersetzen.","insightFit":"Performance Activation & Weekly Action Intelligence","questions":["Wissen Teams, was sie nächste Woche tun müssen?","Werden Insights in Store Meetings verfolgt?","Kann das Management Aktionen priorisieren?"]},
    "centre_baseline": {"title":"Wir können nicht belegen, wie sich das Center über Zeit entwickelt","pain":"Besucherzahlen existieren eventuell, sind aber nicht immer zuverlässig, vollständig oder vergleichbar genug, um Asset Performance zu steuern.","outcome":"Eine verlässliche Baseline für Gesamtbesuche, Eingänge, Trends und Asset Performance aufbauen.","insightFit":"Centre Performance Baseline","questions":["Wissen wir, ob das Center wirklich wächst oder sinkt?","Sind alle Eingänge zuverlässig gemessen?","Können wir Perioden und Jahre fair vergleichen?"],"modules":["3D Entrance Counting","Centre Dashboard"]},
    "entrance_value": {"title":"Wir wissen nicht, welche Eingänge wirklich Wert schaffen","pain":"Center haben mehrere Eingänge, aber nicht jeder Eingang trägt gleich zu Besuch, Tenant Exposure oder Kampagnenwirkung bei.","outcome":"Pro Eingang zeigen, wo Traffic eintritt, sich verschiebt und Wert für Routing, Tenants und Marketing erzeugt.","insightFit":"Entrance Performance Intelligence","questions":["Welche Eingänge bringen den größten Wert?","Verändert sich Traffic je Kampagne oder Saison?","Welcher Eingang verdient zusätzliche Aktivierung?"],"modules":["Entrance-level Reporting","Benchmark / Index Layer"]},
    "zone_flow": {"title":"Besucher betreten das Center, aber wir wissen nicht, wohin sie gehen","pain":"Korridore, Zonen, Etagen, Toiletten, F&B und Anchor Zones spielen alle eine Rolle, aber der Flow dazwischen ist oft unklar.","outcome":"Zone- und Corridor-Flow messen, um Dichte, Verteilung, Facility-Nutzung und Routing zu verstehen.","insightFit":"Zone Flow Intelligence","questions":["Welche Zonen sind über- oder untergenutzt?","Wo entstehen Bottlenecks oder stille Zonen?","Wie nutzen Besucher Facilities und F&B?"],"modules":["3D Zone Sensors","Zone Dashboard Layer"]},
    "tenant_capture": {"title":"Wir können Tenant Value oder Tenant Capture nicht belegen","pain":"Footfall im Center zeigt noch nicht, welche Mieter Traffic anziehen, profitieren oder Chancen verpassen.","outcome":"Mall Traffic mit Tenant Entrances verbinden, um Capture Rate, Tenant Exposure und Leasinggespräche zu stützen.","insightFit":"Tenant Capture Intelligence","questions":["Welche Mieter ziehen Besucher wirklich hinein?","Welche Mieter verpassen Traffic vor ihrer Tür?","Können wir Tenant-Gespräche mit Daten stützen?"],"modules":["Tenant Counting","Mall-to-Tenant Analytics"]},
    "leasing_evidence": {"title":"Leasinggespräche basieren noch zu stark auf Meinung","pain":"Leerstand, Unit Value und Tenant Mix werden mit Erfahrung diskutiert, aber manchmal fehlen harte Daten zu Traffic, Catchment und Kategoriepotenzial.","outcome":"Leasing Battlecards, Unit Heatmaps und Kategorie-Opportunity-Analysen für fundierte Vermietungsgespräche erstellen.","insightFit":"Leasing Evidence & Unit Value Intelligence","questions":["Welche Units haben verborgenes Potenzial?","Welche Kategorie fehlt im Center?","Welche Daten helfen Leasinggesprächen?"],"modules":["Leasing Battlecard","Unit Heatmap Layer"]},
    "catchment_geo": {"title":"Wir wissen nicht, woher Besucher kommen oder wie sich unser Einzugsgebiet verändert","pain":"Das Center sieht Besucher, aber nicht immer aus welchen Gebieten sie kommen, wie oft sie zurückkehren oder welche Wettbewerbsstandorte sie ebenfalls besuchen.","outcome":"Geo-App-Daten für Catchment, Herkunft, Besuchsfrequenz, Wettbewerbsüberschneidung und Marktentwicklung nutzen.","insightFit":"Catchment & Geo App Intelligence","questions":["Welche Gebiete liefern die meisten Besucher?","Verändert sich das Einzugsgebiet?","Welche Wettbewerber teilen dasselbe Publikum?"],"modules":["Geo App Data","Catchment Dashboard"]},
    "brand_affinity": {"title":"Wir wissen nicht, welche Marken unsere Besucher bereits mögen","pain":"Für Leasing und Tenant Mix ist es wertvoll zu wissen, welche Marken, Kategorien und Zielgruppen zum echten Besucherprofil passen.","outcome":"Brand Affinity, Category Gap und Tenant Mix Analysen nutzen, um bessere Leasingziele und Markenpropositionen zu erstellen.","insightFit":"Brand Affinity & Tenant Mix Intelligence","questions":["Welche Marken passen zu unseren Besuchern?","Welche Kategorien fehlen?","Welche Tenants sollten wir ansprechen?"],"modules":["Brand Affinity Dataset","Tenant Mix Report"]},
    "parking_mobility": {"title":"Wir können Parkdruck und Mobilitätsmuster nicht erklären","pain":"Retail Parks und autoorientierte Center wissen oft, wie viele Autos kommen, aber weniger gut, wann Parkdruck entsteht oder wie lange Fahrzeuge bleiben.","outcome":"Auto-Ein-/Ausfahrten, Belegung und Verweildauer messen, um Parking, Operations und Asset Performance besser zu steuern.","insightFit":"Parking & Mobility Intelligence","questions":["Wann entsteht Parkdruck?","Wie lange bleiben Fahrzeuge durchschnittlich?","Welche Ein- oder Ausfahrten verursachen Reibung?"],"modules":["ANPR / Car Counting","Parking Occupancy"]},
    "anpr_origin": {"title":"Wir wissen zu wenig über internationale Besucher und Fahrzeugherkunft","pain":"Cross-border Assets müssen verstehen, woher Fahrzeuge kommen und wie sich Besucherherkunft je Zeitraum oder Kampagne verändert.","outcome":"Fahrzeugland/-region, internationalen Anteil und Verweildauer je Besuchergruppe zeigen, soweit rechtlich möglich.","insightFit":"ANPR Origin Intelligence","questions":["Welcher Anteil der Fahrzeuge kommt aus anderen Ländern?","Welche Regionen sind am wichtigsten?","Verändert sich internationaler Traffic über Zeit?"],"modules":["ANPR Origin Analytics","Cross-border Reporting"]},
    "dwell_cross_shopping": {"title":"Wir können Dwell Time und Cross-Shopping nicht richtig messen","pain":"Das Center möchte verstehen, ob Besucher länger bleiben, mehrere Tenants besuchen, nur durchlaufen oder später zurückkehren.","outcome":"Dwell Time, Shops per Visit, Cross-Shopping und Besuchsfrequenz mit der richtigen Mischung aus Sensoren, Smart Data und Feasibility Review abschätzen.","insightFit":"Dwell Time & Cross-Shopping Intelligence","questions":["Bleiben Besucher lange genug?","Besuchen sie mehrere Tenants?","Ist Re-ID für dieses Asset machbar und privacy-safe?"],"modules":["Re-ID Feasibility","Dwell Analytics","Cross-Shopping Analysis"]},
    "visitor_profile": {"title":"Wir verstehen Besucherdemografie noch nicht gut genug","pain":"Besucherzahlen sind sichtbar, aber der Mix aus Erwachsenen, Kindern, Familien und Gender-Mustern ist noch nicht Teil der Asset Story.","outcome":"Visitor-Profile-Datasets auf geeigneten 3D-Sensoren aktivieren, um Adult/Child Split, Gender und später Alterskategorien zu verstehen.","insightFit":"Visitor Profile Intelligence","questions":["Zieht das Center Familien an?","Unterscheidet sich das Besucherprofil je Eingang oder Event?","Welche Demografie reagiert auf Kampagnen?"],"modules":["3D Demographics Add-on","Visitor Profile Dashboard"]},
    "event_marketing": {"title":"Wir können Events, Marketing und Offline-Besuche nicht verbinden","pain":"Events und Kampagnen kosten Geld, aber Offline-Wirkung ist häufig schwer in Besuch und Catchment Response nachzuweisen.","outcome":"Event Uplift, Kampagnenresponse, Social/Online-Signale und Offline-Besuche in einer Ansicht messen.","insightFit":"Event & Marketing Impact Intelligence","questions":["Hat das Event Besuche erhöht?","Welche Gebiete reagierten auf Marketing?","Können wir Offline-Wirkung belegen?"],"modules":["Event Monitor","Marketing Impact","Geo Campaign Analysis"]},
    "asset_health": {"title":"Portfolio- und Asset-Teams können Center nicht fair vergleichen","pain":"Mehrere Center und Retail Parks benötigen eine vergleichbare Sicht auf Asset Health, Trend, Forecast und Performance Drivers.","outcome":"Einen Asset Health Score oder Location Vitality Index erstellen, um Center über Zeit zu vergleichen und Treiber zu identifizieren.","insightFit":"Location Vitality Index / Asset Health Intelligence","questions":["Welche Center verbessern sich oder fallen zurück?","Welcher Treiber erklärt den Score?","Können Asset-Teams Äpfel mit Äpfeln vergleichen?"],"modules":["LVI / Asset Health Index","Portfolio Dashboard","Forecasting"]}
  }.items()
}

GOAL["FR"] = {
    k: v for k, v in {
    "baseline_missing": {"title":"Nous n’avons pas de base de performance fiable","pain":"Nous connaissons les ventes ou transactions, mais pas combien de personnes sont réellement entrées. Cela rend la performance magasin difficile à juger.","outcome":"Créer une base fiable pour la fréquentation, la conversion et le potentiel magasin sur chaque site.","insightFit":"Base fiable fréquentation & conversion","questions":["Savez-vous combien de visiteurs sont nécessaires pour générer les ventes du jour ?","Les données sont-elles assez fiables pour comparer les magasins ?","Les équipes magasin voient-elles la même vérité que le siège ?"]},
    "visitors_not_buying": {"title":"Nous avons des visiteurs, mais pas assez d’acheteurs","pain":"Le trafic est visible, mais le moment, le magasin ou la raison de la fuite de conversion reste flou.","outcome":"Identifier quels magasins, jours et heures ont assez de visiteurs mais manquent du potentiel de vente.","insightFit":"Conversion Leak Intelligence","questions":["Quels magasins ont un bon trafic mais des ventes faibles ?","Quand la conversion baisse-t-elle ?","Les équipes voient-elles quoi améliorer la semaine prochaine ?"]},
    "street_vs_store": {"title":"Nous ne savons pas si le problème vient de la rue ou du magasin","pain":"Quand les visites baissent, les équipes ne savent pas si la rue est plus calme ou si le magasin a perdu en attractivité.","outcome":"Séparer la baisse du trafic externe de l’attractivité du magasin et calculer le capture rate par jour, semaine et campagne.","insightFit":"Capture Rate & Street Potential Intelligence","questions":["Moins de personnes entrent-elles parce que la rue est plus calme ?","La vitrine ou la façade attire-t-elle assez de visiteurs ?","Le marketing peut-il prouver qu’il a augmenté les visites en magasin ?"]},
    "groups_distort_conversion": {"title":"Les familles et groupes rendent la conversion moins bonne qu’elle ne l’est","pain":"Un magasin peut sembler faible quand de nombreux visiteurs viennent en famille ou en groupe alors qu’une seule personne est susceptible d’acheter.","outcome":"Ajouter le contexte d’unité d’achat pour rendre les discussions de conversion plus justes et utiles.","insightFit":"Buying Unit Conversion Context","questions":["Le trafic familial pénalise-t-il la conversion du week-end ?","Mesurez-vous des personnes ou de vraies opportunités d’achat ?","Les managers peuvent-ils expliquer la conversion avec contexte ?"]},
    "visitor_profile_unknown": {"title":"Nous ne savons pas qui entre dans nos magasins","pain":"La fréquentation montre combien de personnes entrent, mais pas si le mix visiteurs change par genre, adultes, enfants, familles, groupes ou futures catégories d’âge.","outcome":"Activer des datasets de profil visiteur pour comprendre qui visite, quand le mix change et quels magasins attirent la bonne audience.","insightFit":"Visitor Profile & Demographic Intelligence","questions":["Savez-vous si la bonne audience entre ?","Le mix visiteurs diffère-t-il par magasin, jour ou campagne ?","Les familles et groupes changent-ils la vraie opportunité d’achat ?"]},
    "stores_hard_to_compare": {"title":"Les magasins sont comparés injustement","pain":"Les magasins de centre-ville, destinations, retail parks, sites touristiques et flagships sont souvent comparés comme s’ils opéraient dans les mêmes conditions.","outcome":"Créer des groupes comparables et révéler la vraie sous-performance, le potentiel caché et les écarts de benchmark.","insightFit":"Portfolio Benchmark Intelligence","questions":["Comparez-vous les magasins par type, taille et contexte ?","Quels sites méritent l’attention en premier ?","Les managers régionaux peuvent-ils expliquer les différences de performance ?"]},
    "staffing_feels_reactive": {"title":"La planification du personnel et des moments de service repose trop sur l’intuition","pain":"Les moments chargés sont visibles après coup, mais la capacité de service doit être planifiée avant de perdre l’opportunité commerciale.","outcome":"Aligner staffing, focus service et routines magasin sur la demande réelle, les pics, heures creuses et écarts de conversion.","insightFit":"Store Operations & Service Intelligence","questions":["Quelles heures sont chargées mais commercialement faibles ?","Les plannings reposent-ils sur la demande réelle ?","Où le service peut-il s’améliorer sans deviner ?"]},
    "entrance_bounce": {"title":"Les personnes entrent, hésitent et repartent","pain":"Certains visiteurs franchissent le seuil, regardent l’entrée, rencontrent une friction comme des escaliers ou le layout et repartent avant de devenir une vraie opportunité de vente.","outcome":"Mesurer l’engagement et le bounce à l’entrée pour savoir si les premiers mètres créent ou perdent du potentiel.","insightFit":"Entrance Engagement & Bounce Intelligence","questions":["Les premiers mètres convertissent-ils ou perdent-ils des visiteurs ?","Où la friction apparaît-elle à l’entrée ?","Le layout aide-t-il à continuer le parcours ?"]},
    "instore_unknown": {"title":"Nous ne savons pas ce qui se passe après l’entrée","pain":"Le magasin peut être fréquenté, mais les équipes ne voient pas où les visiteurs vont, ce qu’ils évitent, où ils restent ou quelle catégorie perd de l’attention.","outcome":"Utiliser les insights zones, journeys, heatmaps et dwell pour améliorer layout, exposition catégorie et apprentissages flagship.","insightFit":"In-store Journey & Category Intelligence","questions":["Quelles zones attirent du trafic mais ne convertissent pas ?","Le layout ou la catégorie explique-t-il la performance ?","Quels apprentissages flagship doivent guider les futurs magasins ?"]},
    "expansion_gut_feel": {"title":"Les décisions d’expansion reposent encore trop sur l’intuition","pain":"Les équipes retail choisissent souvent des villes ou rues parce qu’elles semblent bonnes, sans savoir si l’audience, le trafic et le potentiel local correspondent.","outcome":"Appuyer ouvertures, relocalisations et formats avec la logique trafic, catchment et performance.","insightFit":"Location Potential & Expansion Intelligence","questions":["Cette rue correspond-elle à votre profil client ?","Connaissez-vous le trafic attendu avant de signer ?","Où se trouve le plus grand potentiel local ?"]},
    "data_not_activated": {"title":"Les données existent, mais les équipes n’agissent pas assez","pain":"Les dashboards sont disponibles, mais les équipes magasin ont besoin de priorités, recommandations et rythme de suivi plus clairs.","outcome":"Transformer les données en focus hebdomadaire, actions magasin, priorités régionales et conversations management.","insightFit":"Performance Activation & Weekly Action Intelligence","questions":["Les équipes savent-elles quoi faire la semaine prochaine ?","Les insights sont-ils suivis en réunions magasin ?","Le management peut-il prioriser les actions ?"]},
    "centre_baseline": {"title":"Nous ne pouvons pas prouver comment le centre performe dans le temps","pain":"Des chiffres de fréquentation peuvent exister, mais ils ne sont pas toujours fiables, complets ou comparables pour piloter l’asset performance.","outcome":"Construire une baseline fiable pour les visiteurs totaux, les entrées, les tendances et l’asset performance.","insightFit":"Centre Performance Baseline","questions":["Savons-nous si le centre progresse ou décline vraiment ?","Toutes les entrées sont-elles mesurées de façon fiable ?","Pouvons-nous comparer périodes et années équitablement ?"],"modules":["3D Entrance Counting","Centre Dashboard"]},
    "entrance_value": {"title":"Nous ne savons pas quelles entrées créent réellement de la valeur","pain":"Les centres ont plusieurs entrées, mais toutes ne contribuent pas autant à la fréquentation, à l’exposition tenants ou à l’impact campagne.","outcome":"Montrer par entrée où le trafic arrive, se déplace et crée de la valeur pour routing, tenants et marketing.","insightFit":"Entrance Performance Intelligence","questions":["Quelles entrées apportent le plus de valeur ?","Le trafic change-t-il par campagne ou saison ?","Quelle entrée mérite plus d’activation ?"],"modules":["Entrance-level Reporting","Benchmark / Index Layer"]},
    "zone_flow": {"title":"Les visiteurs entrent dans le centre, mais nous ne savons pas où ils vont","pain":"Corridors, zones, étages, toilettes, F&B et anchor zones jouent tous un rôle, mais le flux entre eux reste souvent flou.","outcome":"Mesurer les flux par zone et corridor pour comprendre densité, répartition, usage facilities et routing.","insightFit":"Zone Flow Intelligence","questions":["Quelles zones sont sur- ou sous-utilisées ?","Où apparaissent les bottlenecks ou zones calmes ?","Comment les visiteurs utilisent-ils facilities et F&B ?"],"modules":["3D Zone Sensors","Zone Dashboard Layer"]},
    "tenant_capture": {"title":"Nous ne pouvons pas prouver la valeur tenant ou le tenant capture","pain":"La fréquentation du centre ne montre pas encore quels tenants attirent le trafic, en bénéficient ou manquent des opportunités.","outcome":"Relier le mall traffic aux entrées tenants pour soutenir capture rate, tenant exposure et discussions leasing.","insightFit":"Tenant Capture Intelligence","questions":["Quels tenants attirent vraiment les visiteurs ?","Quels tenants manquent le trafic devant leur porte ?","Pouvons-nous soutenir les conversations tenants avec des données ?"],"modules":["Tenant Counting","Mall-to-Tenant Analytics"]},
    "leasing_evidence": {"title":"Les conversations leasing reposent encore trop sur l’opinion","pain":"Vacance, valeur d’unité et tenant mix sont discutés avec expérience, mais manquent parfois de données solides sur trafic, catchment et potentiel catégorie.","outcome":"Créer des leasing battlecards, unit heatmaps et analyses category opportunity pour des conversations de location mieux fondées.","insightFit":"Leasing Evidence & Unit Value Intelligence","questions":["Quelles unités ont un potentiel caché ?","Quelle catégorie manque dans le centre ?","Quelles données aident les conversations leasing ?"],"modules":["Leasing Battlecard","Unit Heatmap Layer"]},
    "catchment_geo": {"title":"Nous ne savons pas d’où viennent les visiteurs ni comment le catchment évolue","pain":"Le centre voit les visiteurs, mais pas toujours de quelles zones ils viennent, à quelle fréquence ils reviennent ou quels concurrents ils visitent aussi.","outcome":"Utiliser la geo app data pour catchment, origine, fréquence, overlap concurrentiel et évolution de zone de marché.","insightFit":"Catchment & Geo App Intelligence","questions":["Quelles zones apportent le plus de visiteurs ?","Le catchment évolue-t-il ?","Quels concurrents partagent la même audience ?"],"modules":["Geo App Data","Catchment Dashboard"]},
    "brand_affinity": {"title":"Nous ne savons pas quelles marques nos visiteurs aiment déjà","pain":"Pour leasing et tenant mix, il est utile de savoir quelles marques, catégories et audiences correspondent au vrai profil visiteur.","outcome":"Utiliser brand affinity, category gap et tenant mix analyses pour créer de meilleurs objectifs leasing et propositions marques.","insightFit":"Brand Affinity & Tenant Mix Intelligence","questions":["Quelles marques correspondent à nos visiteurs ?","Quelles catégories manquent ?","Quels tenants devons-nous cibler ?"],"modules":["Brand Affinity Dataset","Tenant Mix Report"]},
    "parking_mobility": {"title":"Nous ne pouvons pas expliquer la pression parking et les patterns de mobilité","pain":"Retail parks et centres orientés voiture savent souvent combien de voitures viennent, mais moins bien quand la pression parking apparaît ou combien de temps les véhicules restent.","outcome":"Mesurer entrées/sorties voitures, occupation et dwell véhicule pour mieux piloter parking, operations et asset performance.","insightFit":"Parking & Mobility Intelligence","questions":["Quand la pression parking apparaît-elle ?","Combien de temps les voitures restent-elles en moyenne ?","Quelles entrées ou sorties créent de la friction ?"],"modules":["ANPR / Car Counting","Parking Occupancy"]},
    "anpr_origin": {"title":"Nous ne savons pas assez sur les visiteurs internationaux et l’origine des voitures","pain":"Les assets cross-border doivent comprendre d’où viennent les voitures et comment l’origine visiteurs change par période ou campagne.","outcome":"Afficher pays/région véhicule, part internationale et dwell time par groupe visiteur lorsque légalement possible.","insightFit":"ANPR Origin Intelligence","questions":["Quelle part des voitures vient d’autres pays ?","Quelles régions comptent le plus ?","Le trafic international évolue-t-il dans le temps ?"],"modules":["ANPR Origin Analytics","Cross-border Reporting"]},
    "dwell_cross_shopping": {"title":"Nous ne pouvons pas mesurer correctement dwell time et cross-shopping","pain":"Le centre doit comprendre si les visiteurs restent plus longtemps, visitent plusieurs tenants, ne font que passer ou reviennent plus tard.","outcome":"Estimer dwell time, shops per visit, cross-shopping et fréquence de visite avec le bon mix de capteurs, smart data et feasibility review.","insightFit":"Dwell Time & Cross-Shopping Intelligence","questions":["Les visiteurs restent-ils assez longtemps ?","Visitent-ils plusieurs tenants ?","La Re-ID est-elle faisable et privacy-safe pour cet asset ?"],"modules":["Re-ID Feasibility","Dwell Analytics","Cross-Shopping Analysis"]},
    "visitor_profile": {"title":"Nous ne comprenons pas assez bien la démographie visiteurs","pain":"Les volumes visiteurs sont visibles, mais le mix adultes, enfants, familles et patterns de genre ne fait pas encore partie de l’asset story.","outcome":"Activer des datasets visitor profile sur les capteurs 3D adaptés pour comprendre adult/child split, genre et plus tard catégories d’âge.","insightFit":"Visitor Profile Intelligence","questions":["Le centre attire-t-il des familles ?","Le profil visiteur diffère-t-il par entrée ou événement ?","Quelle démographie répond aux campagnes ?"],"modules":["3D Demographics Add-on","Visitor Profile Dashboard"]},
    "event_marketing": {"title":"Nous ne pouvons pas relier events, marketing et visites offline","pain":"Events et campagnes coûtent de l’argent, mais leur impact offline est souvent difficile à prouver en trafic et réponse catchment.","outcome":"Mesurer event uplift, réponse campagne, signaux sociaux/online et visites offline dans une seule vue.","insightFit":"Event & Marketing Impact Intelligence","questions":["L’événement a-t-il augmenté les visites ?","Quelles zones ont répondu au marketing ?","Pouvons-nous prouver l’impact offline ?"],"modules":["Event Monitor","Marketing Impact","Geo Campaign Analysis"]},
    "asset_health": {"title":"Les équipes portfolio et asset ne peuvent pas comparer les centres équitablement","pain":"Plusieurs centres et retail parks ont besoin d’une vue comparable de l’asset health, tendance, forecast et drivers de performance.","outcome":"Créer un asset health score ou Location Vitality Index pour comparer les centres dans le temps et identifier les drivers.","insightFit":"Location Vitality Index / Asset Health Intelligence","questions":["Quels centres s’améliorent ou déclinent ?","Quel driver explique le score ?","Les équipes asset peuvent-elles comparer à périmètre équivalent ?"],"modules":["LVI / Asset Health Index","Portfolio Dashboard","Forecasting"]}
    }.items()
}

PACKAGE = {
  "NL": {
    "starter": {"name":"Essential","headline":"Meet de basis betrouwbaar","promise":"Voor retailers die eerst een betrouwbare basis nodig hebben voor winkeltraffic en conversiepotentieel.","contains":["Advantage Portal","Datamanagement","Footfall","Portfolio-breed rapport","Sensorbeheer","Remote support","Conversieratio"]},
    "performance": {"name":"Professional","headline":"Begrijp wie bezoekt en wat hen aantrekt","promise":"Voor retailers die bezoekersprofielen, capture-rate context en rijkere performanceverklaring willen.","contains":["Essential inbegrepen","Leeftijd / gender / groepsopties","Bezetting","Capture rate"]},
    "intelligence": {"name":"Enterprise","headline":"Analyseer journeys, zones en winkelgedrag","promise":"Voor retailers die in-store analytics, zoning, dwell, Re-ID feasibility of advanced reporting willen.","contains":["Professional inbegrepen","Re-ID / dwell","Heat mapping","Conversierapport met salesdata"]}
  },
  "DE": {
    "starter": {"name":"Essential","headline":"Die Basis zuverlässig messen","promise":"Für Händler, die zuerst eine verlässliche Basis für Store Traffic und Conversion-Potenzial benötigen.","contains":["Advantage Portal","Datenmanagement","Footfall","Portfolio-weiter Report","Sensor Management","Remote Support","Conversion Rate"]},
    "performance": {"name":"Professional","headline":"Verstehen, wer besucht und was anzieht","promise":"Für Händler, die Besucherprofile, Capture-Rate-Kontext und eine reichere Performance-Erklärung wollen.","contains":["Essential enthalten","Alter / Gender / Gruppenoptionen","Occupancy","Capture Rate"]},
    "intelligence": {"name":"Enterprise","headline":"Journeys, Zonen und In-store Verhalten analysieren","promise":"Für Händler, die In-store Analytics, Zoning, Dwell, Re-ID-Feasibility oder erweitertes Reporting wollen.","contains":["Professional enthalten","Re-ID / Dwell","Heat Mapping","Conversion Report mit Sales Data"]}
  },
  "FR": {
    "starter": {"name":"Essential","headline":"Mesurer la base de façon fiable","promise":"Pour les retailers qui ont d’abord besoin d’une base fiable pour le trafic magasin et le potentiel de conversion.","contains":["Advantage Portal","Gestion des données","Footfall","Rapport portfolio","Gestion capteurs","Support à distance","Taux de conversion"]},
    "performance": {"name":"Professional","headline":"Comprendre qui visite et ce qui attire","promise":"Pour les retailers qui veulent des profils visiteurs, le contexte capture rate et une explication de performance plus riche.","contains":["Essential inclus","Options âge / genre / groupe","Occupation","Capture rate"]},
    "intelligence": {"name":"Enterprise","headline":"Analyser journeys, zones et comportement en magasin","promise":"Pour les retailers qui veulent in-store analytics, zoning, dwell, faisabilité Re-ID ou reporting avancé.","contains":["Professional inclus","Re-ID / dwell","Heat mapping","Rapport de conversion avec sales data"]}
  }
}

patch = "\n    // v40: explicit dynamic content translations for NL/DE/FR.\n"
for lang, data in GOAL.items():
    patch += f"    Object.assign(GOAL_I18N.{lang}, " + json.dumps(data, ensure_ascii=False) + ");\n"
patch += "\n"

pkg_patch = "\n    // v40: explicit route package translations for NL/DE/FR.\n"
for lang, data in PACKAGE.items():
    pkg_patch += f"    Object.assign(PACKAGE_I18N.{lang} || (PACKAGE_I18N.{lang} = {{}}), " + json.dumps(data, ensure_ascii=False) + ");\n"
pkg_patch += "\n"

Path('/mnt/data/work_v40/i18n_goal_patch.js').write_text(patch, encoding='utf-8')
Path('/mnt/data/work_v40/i18n_package_patch.js').write_text(pkg_patch, encoding='utf-8')
print('goal patch chars', len(patch), 'package patch chars', len(pkg_patch))
